apiVersion: v1
kind: Service
metadata:
  labels:
    app: memsql-leaf1
  name: memsql-leaf1
spec:
  ports:
  - name: 9000-tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: 9022-tcp
    port: 9022
    protocol: TCP
    targetPort: 9022
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: 3307-tcp
    port: 3307
    protocol: TCP
    targetPort: 3307
  selector:
    app: memsql-leaf1
    deploymentconfig: memsql-leaf1
  sessionAffinity: None
  type: ClusterIP
