apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: php
  name: php
spec:
  output:
    to:
      kind: ImageStreamTag
      name: php:latest
  resources: {}
  source:
    git:
      ref: master
      uri: https://github.com/weepee-org/openshift-example-project.git
    contextDir: php/
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: php-webserver:latest
        namespace: weepee-registry
    type: Docker
